-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 29, 2023 at 08:32 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `map_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `india_map`
--

CREATE TABLE `india_map` (
  `color_code` varchar(10) NOT NULL,
  `state` varchar(20) NOT NULL,
  `data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`data`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `india_map`
--

INSERT INTO `india_map` (`color_code`, `state`, `data`) VALUES
('#093c5c', 'Sikkim', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Pakyong Airport\",\r\n      \"address\": \"Pakyong\"\r\n    }\r\n\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Foodniks Restaurant\",\r\n      \"address\": \"Gangtok\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Hamaro Bhansoghaar\",\r\n      \"address\": \"Gangtok\" \r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Rasileeo Family Restaurant\",\r\n      \"address\": \"Gangtok\"\r\n    }\r\n   ]\r\n}'),
('#0cff00', 'West Bengal', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Netaji Subhash Chandra Bose International Airport\",\r\n      \"address\": \"Kolkata\"\r\n    },\r\n    {\r\n     \"id\": 2,\r\n      \"name\": \"Balurghat Airport\",\r\n      \"address\": \"Balurghat\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Alfresco\",\r\n      \"address\": \"Kolkata\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Adveih\",\r\n      \"address\": \"Kolkata\" \r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"First Innings\",\r\n      \"address\": \"Kolkata\"\r\n    }\r\n   ]\r\n}'),
('#15389d', 'Madhya Pradesh', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Jabalpur Airport\",\r\n      \"address\": \"Jabalpur\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Gwalior Airport\",\r\n      \"address\": \"Gwalior\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Indore Airport\",\r\n      \"address\": \"Indore\"\r\n    },\r\n    {\r\n      \"id\": 4,\r\n      \"name\": \"Rajaboj Airport\",\r\n      \"address\": \"Bhopal\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Aura Restaurant and Grill\",\r\n      \"address\": \"Bhopal\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Sanchi\",\r\n      \"address\": \"Indore\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Chula Chowka Restaurant\",\r\n      \"address\": \"Saliwada\"\r\n    }\r\n   ]\r\n}'),
('#229403', 'Manipur', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Bir Tikendrajit International Airport\",\r\n      \"address\": \"Imphal\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Flavours Restaurant\",\r\n      \"address\": \"Imphal\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"The House by Route 39\",\r\n      \"address\": \"Imphal\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Shosa Kitchen\",\r\n      \"address\": \"Imphal\"\r\n    }\r\n   ]\r\n}'),
('#2674ff', 'Ladakh', '{\r\n\"airport_details\" : [\r\n      {\"id\":1, \"name\": \"Kushok Bakula Rimpochee Airport\", \"address\":\"Leh\"}\r\n ],\r\n\"restaurant_details\" : [\r\n      {\"id\":1, \"name\": \"Lamayuru Restaurant\", \"address\":\"Leh\"},\r\n      {\"id\":2, \"name\": \"The Tibetan Kitchen\", \"address\":\"Leh\"},\r\n      {\"id\":2, \"name\": \"Palkhang Restaurant\", \"address\":\"Leh\"}\r\n]\r\n}'),
('#2af9d9', 'Bihar', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Muzaffarpur Airport\",\r\n      \"address\": \"Muzaffarpur\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Raxaul Airport\",\r\n      \"address\": \"Raxaul\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Jaiprakash Narayan Airport\",\r\n      \"address\": \"Patna\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Spice Court\",\r\n      \"address\": \"Patna\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Naushijaan\",\r\n      \"address\": \"Patna\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Bansi Vihar Restaurant\",\r\n      \"address\": \"Patna\"\r\n    }\r\n   ]\r\n}'),
('#42c642', 'Goa', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Goa International Airport\",\r\n      \"address\": \"Dabolim\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Manohar International Airport\",\r\n      \"address\": \"Mopa\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Ritz Classic\",\r\n      \"address\": \"Panjim\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Kismoor\",\r\n      \"address\": \"Porvorim\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Mickeys\",\r\n      \"address\": \"Colva\"\r\n    }\r\n   ]\r\n}'),
('#589dfc', 'Odisha', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Biju Patnaik International Airport\",\r\n      \"address\": \"Odisha\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Veer Surendra Sai Airport\",\r\n      \"address\": \"Jharsuguda\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Savitri Jindal Airport\",\r\n      \"address\": \"Jindal\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Jugaad Jn\",\r\n      \"address\": \"Bhuvaneshwar\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Tapri Legacy\",\r\n      \"address\": \"Bhuvaneshwar\" \r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Malva Restaurant\",\r\n      \"address\": \"Bhuvaneshwar\"\r\n    }\r\n   ]\r\n}'),
('#5d6c00', 'Tamil Nadu', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Chennai International Airport\",\r\n      \"address\": \"Chennai\"\r\n    },\r\n    {\r\n     \"id\": 2,\r\n      \"name\": \"Madurai Airport\",\r\n      \"address\": \"Madurai\"\r\n    },\r\n    {\r\n     \"id\": 3,\r\n      \"name\": \"Truchirapalli International Airport\",\r\n      \"address\": \"Truchirapalli\"\r\n    },\r\n    {\r\n     \"id\": 4,\r\n      \"name\": \"Chettinad Airport\",\r\n      \"address\": \"Chettinad\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Paprika\",\r\n      \"address\": \"Chennai\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"The Flying Elephant\",\r\n      \"address\": \"Chennai\" \r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Seasonal Tastes\",\r\n      \"address\": \"Chennai\"\r\n    }\r\n   ]\r\n}'),
('#6e80b8', 'Nagaland', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Dimapur Airport\",\r\n      \"address\": \"Nagaland\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Skyview\",\r\n      \"address\": \"Nagaland\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Naga Ambrosian Fiesta\",\r\n      \"address\": \"Nagaland\" \r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Bistro29\",\r\n      \"address\": \"Nagaland\"\r\n    }\r\n   ]\r\n}'),
('#70b4aa', 'Mizoram', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Lengpui Airport\",\r\n      \"address\": \"Mamit\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Mizodiner\",\r\n      \"address\": \"Mizoram\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Setha Restaurant\",\r\n      \"address\": \"Mizoram\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Jojo\'s Cafe\",\r\n      \"address\": \"Mizoram\"\r\n    }\r\n   ]\r\n}'),
('#78113d', 'Assam', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Lokpriya Gopinath Bordoloi International Airport\",\r\n      \"address\": \"Guwahati\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Jorhat Airport\",\r\n      \"address\": \"Guwahati\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Lilabari Airport\",\r\n      \"address\": \"Salonibari\"\r\n    },\r\n    {\r\n      \"id\": 4,\r\n      \"name\": \"Silchar Airport\",\r\n      \"address\": \"Silchar\"\r\n    }\r\n\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Athmangala Restaurant\",\r\n      \"address\": \"Guwahati\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"The Table\",\r\n      \"address\": \"Guwahati\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Heritage Khorikaa\",\r\n      \"address\": \"Guwahati\"\r\n    }\r\n   ]\r\n}'),
('#7e7e7e', 'Maharashtra', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Chhatrapati Shivaji Maharaj International Airport\",\r\n      \"address\": \"Mumbai\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Dr. Ambedkar International Airport\",\r\n      \"address\": \"Nagpur\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Mumbai Airport\",\r\n      \"address\": \"Mumbai\"\r\n    },\r\n    {\r\n      \"id\": 4,\r\n      \"name\": \"Aurangabad Airport\",\r\n      \"address\": \"Aurangabad\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Tresind Mumbai\",\r\n      \"address\": \"Mumbai\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Hitchki\",\r\n      \"address\": \"Mumbai\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Yauatcha\",\r\n      \"address\": \"Mumbai\"\r\n    }\r\n   ]\r\n}'),
('#94cbb3', 'Uttarakhand', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Jolly Grant Airport\",\r\n      \"address\": \"Dehradun\"\r\n    },\r\n    {\r\n     \"id\": 2,\r\n      \"name\": \"Maa Ganga Airport\",\r\n      \"address\": \"Uttarakshi\"\r\n    },\r\n    {\r\n     \"id\": 3,\r\n      \"name\": \"Pantnagar Airport\",\r\n      \"address\": \"Pantnagar\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Black Pepper Restaurant\",\r\n      \"address\": \"Dehradun\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Orchard Restaurant\",\r\n      \"address\": \"Dehradun\" \r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Punjab Grill Restaurant\",\r\n      \"address\": \"Dehradun\"\r\n    }\r\n   ]\r\n}'),
('#969f5d', 'Tripura', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Maharaja Bir Bikram Airport\",\r\n      \"address\": \"Tripura\"\r\n    },\r\n    {\r\n     \"id\": 2,\r\n      \"name\": \"Kamlapur Airport\",\r\n      \"address\": \"Kamlapur\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"HML Rooftop Restaurant\",\r\n      \"address\": \"Tripura\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Heritage Restaurant\",\r\n      \"address\": \"Tripura\" \r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"The Fern Restaurant\",\r\n      \"address\": \"Tripura\"\r\n    }\r\n   ]\r\n}'),
('#9e44d0', 'Chhattisgarh', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Bilasa Devi Kevit Airport\",\r\n      \"address\": \"Bilaspur\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Swami Vivekananda Airport\",\r\n      \"address\": \"Raipur\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Maa Danteshwari Airport\",\r\n      \"address\": \"Jagadalpur\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Level 3 Restaurant\",\r\n      \"address\": \"Ama Seoni\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Barbeque Nation\",\r\n      \"address\": \"Lalbandi\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Gadh Kalewa\",\r\n      \"address\": \"Raipur\"\r\n    }\r\n   ]\r\n}'),
('#9f7e4f', 'Rajasthan', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Jaipur International Airport\",\r\n      \"address\": \"Jaipur\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Maharana Pratap Airport\",\r\n      \"address\": \"Udaipur\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Jodhpur Airport\",\r\n      \"address\": \"Jodhpur\"\r\n    },\r\n    {\r\n      \"id\": 4,\r\n      \"name\": \"Jaisalmer Airport\",\r\n      \"address\": \"Jaisalmer\"\r\n    }\r\n\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Steam Restaurant\",\r\n      \"address\": \"Jaipur\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Gulabi Nagri\",\r\n      \"address\": \"Jaipur\" \r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"1135 AD\",\r\n      \"address\": \"Jaipur\"\r\n    }\r\n   ]\r\n}'),
('#a200a8', 'Karnataka', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Kempegowda International Airport\",\r\n      \"address\": \"Bengaluru\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Mysore Airport\",\r\n      \"address\": \"Mysore\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Hubballi Airport\",\r\n      \"address\": \"Hubballi\"\r\n    },\r\n    {\r\n      \"id\": 4,\r\n      \"name\": \"Shivamogga Airport\",\r\n      \"address\": \"Hubballi\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Socials\",\r\n      \"address\": \"Church St, Bengaluru\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Brick Oven\",\r\n      \"address\": \"Church St, Bengaluru\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Konark\",\r\n      \"address\": \"Richmond Rd, Bengaluru\"\r\n    }\r\n   ]\r\n}'),
('#a63c5e', 'Telangana', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Rajiv Gandhi International Airport\",\r\n      \"address\": \"Hyderabad\"\r\n    },\r\n    {\r\n     \"id\": 2,\r\n      \"name\": \"Warangal Airport\",\r\n      \"address\": \"Warangal\"\r\n    },\r\n    {\r\n     \"id\": 3,\r\n      \"name\": \"Ramagundam Airport\",\r\n      \"address\": \"Ramagundam\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Paradise\",\r\n      \"address\": \"Hyderabad\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Jewel of Nizzam\",\r\n      \"address\": \"Hyderabad\" \r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Bidri\",\r\n      \"address\": \"Hyderabad\"\r\n    }\r\n   ]\r\n}'),
('#bc9547', 'Andaman & Nicobar', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Veer Savarkar International Airport\",\r\n      \"address\": \"Andaman Islands\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Andaman and Nicobar Islands Airport\",\r\n      \"address\": \"Andaman and Nicobar\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Chidiya Tapu Heliport\",\r\n      \"address\": \"Port Blair\"\r\n    },\r\n    {\r\n      \"id\": 4,\r\n      \"name\": \"Hut Bay Airport\",\r\n      \"address\": \"Kwate-Tu-Kwage\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Andaman Kitchen\",\r\n      \"address\": \"Port Blair\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Hotel Kattabomman\",\r\n      \"address\": \"Port Blair\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Anju Coco Resto\",\r\n      \"address\": \"Havelock Island\"\r\n    }\r\n   ]\r\n}'),
('#bdcc61', 'Uttar Pradesh', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Chaudhary Charan Singh International Airport\",\r\n      \"address\": \"Kushinagar\"\r\n    },\r\n    {\r\n     \"id\": 2,\r\n      \"name\": \"Kanpur Airport\",\r\n      \"address\": \"Kanpur\"\r\n    },\r\n    {\r\n     \"id\": 3,\r\n      \"name\": \"Agra Airport\",\r\n      \"address\": \"Agra\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Milan Speciality Restaurant\",\r\n      \"address\": \"Lucknow\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Falak Numa Restaurant\",\r\n      \"address\": \"Lucknow\" \r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Farzi Cafe\",\r\n      \"address\": \"Lucknow\"\r\n    }\r\n   ]\r\n}'),
('#c4b0cf', 'Jammu and Kashmir', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Jammu Airport\",\r\n      \"address\": \"Jammu\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Srinagar International Airport\",\r\n      \"address\": \"Srinagar\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Rajouri Airport\",\r\n      \"address\": \"Rajouri\"\r\n    },\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Satwari Airport\",\r\n      \"address\": \"Satwari\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Zamindara Dhaba\",\r\n      \"address\": \"Samba, J&K\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Barbeque Nation\",\r\n      \"address\": \"Jammu, J&K\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Grill n Chill\",\r\n      \"address\": \"J&K\"\r\n    }\r\n    \r\n    ]\r\n}'),
('#cf484b', 'Meghalaya', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Shillong Airport\",\r\n      \"address\": \"Shillong\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Beso Bistro\",\r\n      \"address\": \"Shillong\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Dejavu Restaurant\",\r\n      \"address\": \"Shillong\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"City Hut Family Dhaba\",\r\n      \"address\": \"Shillong\"\r\n    }\r\n   ]\r\n}'),
('#dd3109', 'Gujarat', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Bhavnagar Airport\",\r\n      \"address\": \"Bhavnagar\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Sardar Vallabhbhai International Airport\",\r\n      \"address\": \"Surat\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Vadodara Airport\",\r\n      \"address\": \"Vadodara\"\r\n    },\r\n    {\r\n      \"id\": 4,\r\n      \"name\": \"Surat International Airport\",\r\n      \"address\": \"Surat\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Swad Restaurant\",\r\n      \"address\": \"GT Road\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Silverspoon Restaurant\",\r\n      \"address\": \"Bhimbar Road\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Haveli Family Restaurant\",\r\n      \"address\": \"Sarwar Gold Plaza\"\r\n    }\r\n   ]\r\n}'),
('#e7c57d', 'Arunachal Pradesh', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Tizu Airport\",\r\n      \"address\": \"Tizu\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Donyi Polo Airport\",\r\n      \"address\": \"Itanagar\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Pasighat Airport\",\r\n      \"address\": \"Pasighat\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Kori\'s Restaurant\",\r\n      \"address\": \"Naharlagun\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Dalnor Restaurant\",\r\n      \"address\": \"Naharlagun\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Pisi\'s Restaurant\",\r\n      \"address\": \"Miao\"\r\n    }\r\n   ]\r\n}'),
('#e825cf', 'Delhi', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Indira Gandhi International Airport\",\r\n      \"address\": \"New Delhi\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"The GT Road\",\r\n      \"address\": \"New Delhi\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Tamra Restaurant\",\r\n      \"address\": \"New Delhi\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Olive Bar & Kitchen\",\r\n      \"address\": \"New Delhi\"\r\n    }\r\n   ]\r\n}'),
('#eb2e6b', 'Jharkhand', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Deoghar Airport\",\r\n      \"address\": \"Jharkhand\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Birsa Munda Airport\",\r\n      \"address\": \"Ranchi\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Sonari Airport\",\r\n      \"address\": \"Jharkhand\"\r\n    },\r\n    {\r\n      \"id\": 4,\r\n      \"name\": \"Bokaro Airport\",\r\n      \"address\": \"Jharkhand\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Seventh Heaven Restaurant\",\r\n      \"address\": \"Ranchi\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Ten 11 Restaurant and Bar\",\r\n      \"address\": \"Ranchi\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Sigree\",\r\n      \"address\": \"Ranchi\"\r\n    }\r\n   ]\r\n}'),
('#edea9e', 'Kerala', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Thiruvananthapuram International Airport\",\r\n      \"address\": \"Thiruvananthapuram\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Cochin International Airport\",\r\n      \"address\": \"Cochin\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Calicut International Airport\",\r\n      \"address\": \"Calicut\"\r\n    },\r\n    {\r\n      \"id\": 4,\r\n      \"name\": \"Kannur International Airport\",\r\n      \"address\": \"Kannur\"\r\n    }\r\n\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Zoka\",\r\n      \"address\": \"Ernakulam\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Ginger House\",\r\n      \"address\": \"Kochi\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Fusion Bay\",\r\n      \"address\": \"Kochi\"\r\n    }\r\n   ]\r\n}'),
('#efb256', 'Haryana', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Karnal Airport\",\r\n      \"address\": \"Ambala\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Bhivani Airport\",\r\n      \"address\": \"Karnal\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Shaheed Bhagat Singh International Airport\",\r\n      \"address\": \"Karnal\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Roof Pie Cafe amd Restaurant\",\r\n      \"address\": \"Jind\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Under the Neem\",\r\n      \"address\": \"Gurugram\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Twenty One Gun Salute\",\r\n      \"address\": \"Gurugram\"\r\n    }\r\n   ]\r\n}'),
('#f6a1bc', 'Himachal Pradesh', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Bhuntar Airport\",\r\n      \"address\": \"Kangra\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Kangra Airport\",\r\n      \"address\": \"Kangra\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Shimla Airport\",\r\n      \"address\": \"Shimla\"\r\n    },\r\n    {\r\n      \"id\": 4,\r\n      \"name\": \"Patankhot Airport\",\r\n      \"address\": \"Shimla\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Hill Top Restaurant\",\r\n      \"address\": \"Himachal\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Nirvana Deluxe Rooftop\",\r\n      \"address\": \"Bashisht\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Himachali Rasoi\",\r\n      \"address\": \"Shimla\"\r\n    }\r\n   ]\r\n}'),
('#ff0000', 'Punjab', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Shri Guru Ram Das Jee International Airport\",\r\n      \"address\": \"Patiala\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Pathankot Airport\",\r\n      \"address\": \"Pathankot\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Amritsar Airport\",\r\n      \"address\": \"Amritsar\"\r\n    },\r\n    {\r\n      \"id\": 4,\r\n      \"name\": \"Chandigarh International Airport\",\r\n      \"address\": \"Chandigarh\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Hitchki Restaurant\",\r\n      \"address\": \"Jalandar\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Brick House Kitchen\",\r\n      \"address\": \"Amritsar\" \r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Blaase\",\r\n      \"address\": \"Ludhiana\"\r\n    }\r\n   ]\r\n}'),
('#ff6c00', 'Andhra Pradesh', '{\r\n  \"airport_details\": [\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Vijayawada International Airport\",\r\n      \"address\": \"Vijayawada\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Chuddapah Airport\",\r\n      \"address\": \"Kadapa\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Visakhapatnam Airport\",\r\n      \"address\": \"Visakhapatnam\"\r\n    },\r\n    {\r\n      \"id\": 4,\r\n      \"name\": \"Tirupati Airport\",\r\n      \"address\": \"Tirupati\"\r\n    }\r\n  ],\r\n  \"restaurant_details\":[\r\n    {\r\n      \"id\": 1,\r\n      \"name\": \"Dakshin Restaurant\",\r\n      \"address\": \"Visakhapatnam\"\r\n    },\r\n    {\r\n      \"id\": 2,\r\n      \"name\": \"Nandi Aahar Restaurant\",\r\n      \"address\": \"Karnatakanagepalli\"\r\n    },\r\n    {\r\n      \"id\": 3,\r\n      \"name\": \"Le Story Restaurant\",\r\n      \"address\": \"Vijayawada\"\r\n    }\r\n   ]\r\n}');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `india_map`
--
ALTER TABLE `india_map`
  ADD PRIMARY KEY (`color_code`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
